# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('event_start', models.DateField(blank=True, null=True)),
                ('event_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='position',
        ),
        migrations.AddField(
            model_name='event',
            name='places',
            field=models.ManyToManyField(to='events.Place'),
        ),
    ]
