# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20161102_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start', models.DateField(blank=True, null=True)),
                ('event_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='places',
        ),
        migrations.RemoveField(
            model_name='place',
            name='event_end',
        ),
        migrations.RemoveField(
            model_name='place',
            name='event_start',
        ),
        migrations.AddField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Place'),
        ),
    ]
