# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20161102_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='parent',
        ),
        migrations.AddField(
            model_name='event',
            name='places',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Place'),
        ),
        migrations.AddField(
            model_name='place',
            name='schedules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Schedule'),
        ),
    ]
