# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_placeschedule_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='event_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='event_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
