# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20161102_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeschedule',
            name='schedules',
            field=models.ManyToManyField(blank=True, to='events.Schedule'),
        ),
    ]
