# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20161102_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='PlaceSchedule',
        ),
        migrations.AddField(
            model_name='event',
            name='PlaceSchedule',
            field=models.ManyToManyField(blank=True, to='events.PlaceSchedule'),
        ),
    ]
