# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20161102_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('attachment', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
