# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_galery'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
