# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_galery_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attachment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
