# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
