# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161027_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nit',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
