# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161027_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nit',
            field=models.CharField(max_length=20),
        ),
    ]
